"""Bridge frame v0 codec for MeshCore ↔ bitchat bridge MVP."""

from .bitchat_packet_fixture import (
    BITCHAT_MESSAGE_TYPE_MESSAGE,
    BITCHAT_PACKET_VERSION_V1,
    BITCHAT_RECIPIENT_BROADCAST,
    BITCHAT_SIGNATURE_SIZE,
    BitchatPacketFixture,
    BitchatPacketFixtureError,
    decode_raw_v1_packet_fixture,
    make_android_public_message_fixture,
    make_ios_public_message_fixture,
)
from .bitchat_text import (
    BitchatOutboundText,
    BitchatPublishedText,
    BitchatTextCarrier,
    FakeBitchatTextCarrier,
)
from .bridge_pump import BridgePumpResult, pump_text_bridge_once
from .bridge_frame import (
    BridgeFrame,
    BridgeFrameError,
    MAGIC,
    VERSION,
    MAX_CARRIER_PAYLOAD,
    FIXED_OVERHEAD,
    MAX_FRAME_PAYLOAD,
    crc16_xmodem,
    encode_frame,
    decode_frame,
    fragment_payload,
    reassemble_fragments,
)
from .message import frames_to_text, max_text_bytes, text_to_frames
from .meshcore_companion import (
    CMD_SEND_CHANNEL_DATA,
    DATA_TYPE_DEV,
    FLOOD_PATH,
    RESP_CODE_CHANNEL_DATA_RECV,
    InboundChannelData,
    build_channel_data_command,
    parse_channel_data_recv,
)
from .serial_adapter import (
    InMemorySerialByteStream,
    MAX_SERIAL_PAYLOAD,
    SERIAL_RX_START,
    SERIAL_TX_START,
    SerialCompanionDatagramTransport,
    SerialRxPacketReader,
    unwrap_serial_tx_packet,
    wrap_serial_rx_packet,
    wrap_serial_tx_packet,
)
from .sim import DeliveredText, SimulatedBridgeNode, SimulatedMeshCoreLink
from .transport import (
    CompanionDatagramTransport,
    FakeCompanionDatagramTransport,
    drain_transport_to_node,
    send_text_over_transport,
)

__all__ = [
    "BITCHAT_MESSAGE_TYPE_MESSAGE",
    "BITCHAT_PACKET_VERSION_V1",
    "BITCHAT_RECIPIENT_BROADCAST",
    "BITCHAT_SIGNATURE_SIZE",
    "BitchatPacketFixture",
    "BitchatPacketFixtureError",
    "decode_raw_v1_packet_fixture",
    "make_android_public_message_fixture",
    "make_ios_public_message_fixture",
    "BitchatOutboundText",
    "BitchatPublishedText",
    "BitchatTextCarrier",
    "FakeBitchatTextCarrier",
    "BridgePumpResult",
    "pump_text_bridge_once",
    "BridgeFrame",
    "BridgeFrameError",
    "MAGIC",
    "VERSION",
    "MAX_CARRIER_PAYLOAD",
    "FIXED_OVERHEAD",
    "MAX_FRAME_PAYLOAD",
    "crc16_xmodem",
    "encode_frame",
    "decode_frame",
    "fragment_payload",
    "reassemble_fragments",
    "frames_to_text",
    "max_text_bytes",
    "text_to_frames",
    "CMD_SEND_CHANNEL_DATA",
    "DATA_TYPE_DEV",
    "FLOOD_PATH",
    "RESP_CODE_CHANNEL_DATA_RECV",
    "InboundChannelData",
    "build_channel_data_command",
    "parse_channel_data_recv",
    "DeliveredText",
    "SimulatedBridgeNode",
    "SimulatedMeshCoreLink",
    "CompanionDatagramTransport",
    "FakeCompanionDatagramTransport",
    "InMemorySerialByteStream",
    "MAX_SERIAL_PAYLOAD",
    "SERIAL_RX_START",
    "SERIAL_TX_START",
    "SerialCompanionDatagramTransport",
    "SerialRxPacketReader",
    "unwrap_serial_tx_packet",
    "drain_transport_to_node",
    "send_text_over_transport",
    "wrap_serial_rx_packet",
    "wrap_serial_tx_packet",
]
